language: node_js
node_js:
    - "0.10"

install:
- npm install
- npm install -g mocha
- npm install -g typings
- npm install -g typescript

script:
    - typings install
    - tsc
    - mocha test/ImportTest.js
